hydra:
  run:
    dir: ./

data_dir: /home/jiaofangkai/IQON_pair_remove_edge

train_file: ${data_dir}/UII_train_quadruple.json
dev_file: ${data_dir}/UII_valid_quadruple.json
test_file: ${data_dir}/test_quadruple.json

embedding_memory:
  _target_: data_loader.data_utils.EmbeddingMatrix
  attr_text: ${data_dir}/subgraphs/attribute_emb_weight.pt
  item_image: ${data_dir}/subgraphs/item_img.pt
  item_text: ${data_dir}/subgraphs/item_text_emb_weight.cls.pt


# Data loading
dataset:
  _target_: data_loader.data_loader_v1.SubgraphDataset
  meta_path_dict:
    ii: ${data_dir}/subgraphs_v1.0.ii
    iia: ${data_dir}/subgraphs_v1.0.iia
    iai: ${data_dir}/subgraphs/subgraph-iai/*
    iui: ${data_dir}/subgraphs_v1.0.iui
    uia: ${data_dir}/subgraphs_v1.0.uia
    uiu: ${data_dir}/subgraphs_v1.0.uiu
    uiaiu: ${data_dir}/subgraphs/subgraph-uiaiu/*
  graph_sampler:
    _target_: data_loader.data_utils.MaximusNeighbourSampler
    max_neighbour_num: 5


# Data collator
collator:
  _target_: data_loader.data_collator_fix_emb.SubgraphCollatorVocab
  user_vocab: ${data_dir}/subgraphs/user_vocab.json
  attr_vocab: ${data_dir}/subgraphs/attribute_vocab.json
  item_vocab: ${data_dir}/subgraphs/item_vocab.json
  node_vocab: ${data_dir}/subgraphs/vocab.pt


# Dataloader
num_workers: 32
eval_num_workers: 0
prefetch_factor: 2

# Model
model:
  _target_: models.gat_tf_emb.GATTransformer
  user_embedding: ${data_dir}/subgraphs/user_emb_weight.pt
  user_vocab: ${collator.user_vocab}
  freeze_user_emb: False
  vision_model: resnet18
  text_hidden_size: 768
  img_hidden_size: 512
  hidden_size: 768
  gnn:
    _target_: models.gat.GAT
    num_layers: 3
    input_size: ${model.hidden_size}
    num_heads: 12
    head_size: 64
    feat_dropout: 0.1
    attn_dropout: 0.1
    residual: True
  transformer:
    _target_: models.transformer.initialize_transformer
    encoder_layers: 2
    encoder_ffn_dim: 3072
    encoder_attention_heads: 12
    encoder_layerdrop: 0.0
    activation_function: "gelu"
    d_model: ${model.hidden_size}
    dropout: 0.1
    attention_dropout: 0.0
    activation_dropout: 0.0
    init_std: 0.02
    classifier_dropout: 0.0

pretrain:

output_dir: experiments/gat_tf_fix_emb.v1.0

do_train: True
evaluate_during_training: True

do_eval: True
eval_sub_path:

# Training hyper-parameters
per_gpu_train_batch_size: 2
per_gpu_eval_batch_size: 2
learning_rate: 5e-5
gradient_accumulation_steps: 16
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 0.0
num_train_epochs: 30
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:

logging_steps: 5
summary_helper:
  _target_: general_util.training_utils.SummaryWriterHelper

save_steps: -1
save_best: True
eval_steps: 1000
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False
move_grads_to_cpu: False
move_params_to_cpu: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
